name: ZxChat
version: '${project.version}'
main: cn.zry551.zxchat.ZxChat
api-version: 1.15
authors: [ ZRY551 ]
description: Make Plugins by Python.
website: https://mcmod.zry551.cn
commands:
  zxchat:
    aliases:
      - "zxchat"
      - "zxc"
    usage: "\u00a7l\u00a73Use : /zxchat <Args>"
    description: "\u00a7l\u00a73/Open Settings GUI."
    permission: "minecraft.command.op"
    permission-message: "\u00a7l\u00a73/You can't do that!"
  zxchatadmin:
    aliases:
      - "zxchatadmin"
      - "zxca"
      - "zxcadmin"
    usage: "\u00a7l\u00a73Use : /zxchatadmin <Args>"
    description: "\u00a7l\u00a73/Open Settings GUI or Debug Mode."
    permission: "minecraft.command.op"
    permission-message: "\u00a7l\u00a73/Only Admin can do that!"
  zxchatsmall:
    aliases:
      - "zxchatsmall"
      - "zxcs"
      - "zxcsmall"
    usage: "\u00a7l\u00a73Use : /zxchatsmall <Args>"
    description: "\u00a7l\u00a73/Open Settings GUI."
    #permission: "minecraft.command.op"
    permission-message: "\u00a7l\u00a73/You can't do that!"
