Format: "\u00a7l[\u00a76%1$s\u00a7r\u00a7l]\u00a7r \u00a7a%2$s"
CallNameFormat: "\u00a7l[\u00a76%1$s\u00a7r\u00a7l<\u00a7r\u00a76#CN\u00a7r\u00a7l>]\u00a7r \u00a7a%2$s"
UseColor: true
UseCallName: true

UseDefaultCallName: false
DefaultCallName: "Player"